-- Seed Citadel Paint Range
INSERT INTO public.paints (brand, name, type, color_hex) VALUES
  -- Base Paints
  ('Citadel', 'Abaddon Black', 'base', '#000000'),
  ('Citadel', 'Averland Sunset', 'base', '#FDB825'),
  ('Citadel', 'Balthasar Gold', 'base', '#A47552'),
  ('Citadel', 'Bugman''s Glow', 'base', '#834437'),
  ('Citadel', 'Caliban Green', 'base', '#00401F'),
  ('Citadel', 'Caledor Sky', 'base', '#396E9A'),
  ('Citadel', 'Castellan Green', 'base', '#264715'),
  ('Citadel', 'Catachan Green', 'base', '#424B0F'),
  ('Citadel', 'Celestra Grey', 'base', '#90A8A0'),
  ('Citadel', 'Ceramite White', 'base', '#FFFFFF'),
  ('Citadel', 'Corax White', 'base', '#FFFFFF'),
  ('Citadel', 'Death Guard Green', 'base', '#556229'),
  ('Citadel', 'Death Korps Drab', 'base', '#3E4539'),
  ('Citadel', 'Deathworld Forest', 'base', '#556229'),
  ('Citadel', 'Gal Vorbak Red', 'base', '#4A1515'),
  ('Citadel', 'Grey Knights Steel', 'base', '#465863'),
  ('Citadel', 'Grey Seer', 'base', '#9FA6A2'),
  ('Citadel', 'Incubi Darkness', 'base', '#0B474A'),
  ('Citadel', 'Jokaero Orange', 'base', '#EE3823'),
  ('Citadel', 'Kantor Blue', 'base', '#00285C'),
  
  -- Layer Paints (abbreviated - add all 100+ layer paints)
  ('Citadel', 'Administratum Grey', 'layer', '#949B9B'),
  ('Citadel', 'Ahriman Blue', 'layer', '#1F8C9C'),
  ('Citadel', 'Alaitoc Blue', 'layer', '#2A5582'),
  ('Citadel', 'Auric Armour Gold', 'layer', '#FFC300'),
  ('Citadel', 'Baharroth Blue', 'layer', '#58C1CD'),
  
  -- Shade Paints
  ('Citadel', 'Agrax Earthshade', 'shade', '#694D2E'),
  ('Citadel', 'Athonian Camoshade', 'shade', '#414837'),
  ('Citadel', 'Biel-Tan Green', 'shade', '#1BA169'),
  ('Citadel', 'Carroburg Crimson', 'shade', '#A4282D'),
  ('Citadel', 'Casandora Yellow', 'shade', '#FFC31B'),
  ('Citadel', 'Coelia Greenshade', 'shade', '#067E4A'),
  ('Citadel', 'Drakenhof Nightshade', 'shade', '#125899'),
  ('Citadel', 'Druchii Violet', 'shade', '#674C7D'),
  ('Citadel', 'Fuegan Orange', 'shade', '#EA8426'),
  ('Citadel', 'Nuln Oil', 'shade', '#14100D'),
  ('Citadel', 'Reikland Fleshshade', 'shade', '#CA6C4D'),
  ('Citadel', 'Seraphim Sepia', 'shade', '#5E4D30'),
  
  -- Dry Paints
  ('Citadel', 'Chronus Blue', 'dry', '#6799BC'),
  ('Citadel', 'Dawnstone', 'dry', '#6D6D6D'),
  ('Citadel', 'Eldar Flesh', 'dry', '#ECC384'),
  ('Citadel', 'Golden Griffon', 'dry', '#C1A880'),
  ('Citadel', 'Hexos Palesun', 'dry', '#FFF571'),
  ('Citadel', 'Kindleflame', 'dry', '#F79646'),
  ('Citadel', 'Longbeard Grey', 'dry', '#CECED0'),
  ('Citadel', 'Lucius Lilac', 'dry', '#B39AC7'),
  ('Citadel', 'Necron Compound', 'dry', '#9B9B9B'),
  ('Citadel', 'Nurgling Green', 'dry', '#9C9E25'),
  ('Citadel', 'Praxeti White', 'dry', '#FFFFFF'),
  ('Citadel', 'Ryza Rust', 'dry', '#EC631E'),
  ('Citadel', 'Sigmarite', 'dry', '#C19F6B'),
  ('Citadel', 'Skink Blue', 'dry', '#65C9D1'),
  ('Citadel', 'Slaanesh Grey', 'dry', '#DDD5D5'),
  ('Citadel', 'Stormfang', 'dry', '#687F8A'),
  ('Citadel', 'Tyrant Skull', 'dry', '#D6D1BD'),
  ('Citadel', 'Underhive Ash', 'dry', '#C4B18F'),
  ('Citadel', 'Verminlord Hide', 'dry', '#602255'),
  
  -- Contrast Paints
  ('Citadel', 'Aggaros Dunes', 'contrast', '#C4A14D'),
  ('Citadel', 'Akelian Green', 'contrast', '#00695C'),
  ('Citadel', 'Apothecary White', 'contrast', '#E0E0E0'),
  ('Citadel', 'Asurmen Blue', 'contrast', '#0A5796'),
  ('Citadel', 'Bad Moon Yellow', 'contrast', '#FFE900'),
  ('Citadel', 'Basilicanum Grey', 'contrast', '#606D75'),
  ('Citadel', 'Black Templar', 'contrast', '#1C1C1C'),
  ('Citadel', 'Blood Angels Red', 'contrast', '#A40000'),
  ('Citadel', 'Creed Camo', 'contrast', '#687C55'),
  ('Citadel', 'Cygor Brown', 'contrast', '#694233'),
  ('Citadel', 'Dark Angels Green', 'contrast', '#004225'),
  ('Citadel', 'Flesh Tearers Red', 'contrast', '#C51618'),
  ('Citadel', 'Garaghak''s Sewer', 'contrast', '#6E6E00'),
  ('Citadel', 'Gore-Grunta Fur', 'contrast', '#6C3A19'),
  ('Citadel', 'Gryph-Charger Grey', 'contrast', '#999999'),
  ('Citadel', 'Gryph-Hound Orange', 'contrast', '#DE6B29'),
  ('Citadel', 'Guilliman Flesh', 'contrast', '#EAA58C'),
  ('Citadel', 'Gutrippa Flesh', 'contrast', '#7D9A53'),
  ('Citadel', 'Iyanden Yellow', 'contrast', '#FFC800'),
  ('Citadel', 'Kroxigor Scales', 'contrast', '#00736B'),
  ('Citadel', 'Leviathan Purple', 'contrast', '#4C3263'),
  ('Citadel', 'Magos Purple', 'contrast', '#70366A'),
  ('Citadel', 'Militarum Green', 'contrast', '#696942'),
  ('Citadel', 'Nazdreg Yellow', 'contrast', '#FFB800'),
  ('Citadel', 'Ork Flesh', 'contrast', '#28843E'),
  ('Citadel', 'Plaguebearer Flesh', 'contrast', '#818D2C'),
  ('Citadel', 'Shyish Purple', 'contrast', '#724070'),
  ('Citadel', 'Sigvald Burgundy', 'contrast', '#6A2134'),
  ('Citadel', 'Skeleton Horde', 'contrast', '#B3A482'),
  ('Citadel', 'Snakebite Leather', 'contrast', '#944E25'),
  ('Citadel', 'Space Wolves Grey', 'contrast', '#6C8590'),
  ('Citadel', 'Stormfiend', 'contrast', '#704E3F'),
  ('Citadel', 'Talassar Blue', 'contrast', '#2068A5'),
  ('Citadel', 'Terradon Turquoise', 'contrast', '#00A19D'),
  ('Citadel', 'Ultramarine Blue', 'contrast', '#01519C'),
  ('Citadel', 'Volupus Pink', 'contrast', '#C3719E'),
  ('Citadel', 'Wyldwood', 'contrast', '#563825')
ON CONFLICT (brand, name) DO NOTHING;