-- Seed paints table with Citadel/Games Workshop paints

INSERT INTO public.paints (brand, name, type, color_hex) VALUES
-- Citadel Base Paints
('Citadel', 'Abaddon Black', 'base', '#000000'),
('Citadel', 'Corax White', 'base', '#FFFFFF'),
('Citadel', 'Averland Sunset', 'base', '#FDB825'),
('Citadel', 'Jokaero Orange', 'base', '#EE3A23'),
('Citadel', 'Mephiston Red', 'base', '#960C09'),
('Citadel', 'Khorne Red', 'base', '#6A0001'),
('Citadel', 'Naggaroth Night', 'base', '#3E3056'),
('Citadel', 'Daemonette Hide', 'base', '#696684'),
('Citadel', 'Kantor Blue', 'base', '#001F44'),
('Citadel', 'Macragge Blue', 'base', '#0E3957'),
('Citadel', 'Caledor Sky', 'base', '#3667A5'),
('Citadel', 'The Fang', 'base', '#405B71'),
('Citadel', 'Thousand Sons Blue', 'base', '#0096C8'),
('Citadel', 'Stegadon Scale Green', 'base', '#07455D'),
('Citadel', 'Caliban Green', 'base', '#003D1D'),
('Citadel', 'Waaagh! Flesh', 'base', '#32623F'),
('Citadel', 'Castellan Green', 'base', '#264715'),
('Citadel', 'Death World Forest', 'base', '#556229'),
('Citadel', 'Zandri Dust', 'base', '#9E8C66'),
('Citadel', 'Steel Legion Drab', 'base', '#5C5038'),
('Citadel', 'Bugman''s Glow', 'base', '#8E503B'),
('Citadel', 'Ratskin Flesh', 'base', '#AA6955'),
('Citadel', 'Mournfang Brown', 'base', '#640D09'),
('Citadel', 'Rhinox Hide', 'base', '#493435'),
('Citadel', 'Dryad Bark', 'base', '#33312B'),
('Citadel', 'Mechanicus Standard Grey', 'base', '#3D4B4E'),
('Citadel', 'Celestra Grey', 'base', '#89A0B2'),
('Citadel', 'Rakarth Flesh', 'base', '#A19D87'),
('Citadel', 'Screamer Pink', 'base', '#7D1F51'),
('Citadel', 'Pink Horror', 'base', '#8F2C6B'),

-- Citadel Layer Paints
('Citadel', 'Evil Sunz Scarlet', 'layer', '#C41518'),
('Citadel', 'Wild Rider Red', 'layer', '#E62F23'),
('Citadel', 'Wazdakka Red', 'layer', '#8C0A0C'),
('Citadel', 'Squig Orange', 'layer', '#A7471B'),
('Citadel', 'Fire Dragon Bright', 'layer', '#F47C21'),
('Citadel', 'Troll Slayer Orange', 'layer', '#EF681D'),
('Citadel', 'Yriel Yellow', 'layer', '#FFD900'),
('Citadel', 'Flash Gitz Yellow', 'layer', '#FFF300'),
('Citadel', 'Altdorf Guard Blue', 'layer', '#18478E'),
('Citadel', 'Calgar Blue', 'layer', '#3A5C86'),
('Citadel', 'Teclis Blue', 'layer', '#3D7DB5'),
('Citadel', 'Lothern Blue', 'layer', '#2C9DBF'),
('Citadel', 'Hoeth Blue', 'layer', '#57A9D6'),
('Citadel', 'Russ Grey', 'layer', '#4F748A'),
('Citadel', 'Fenrisian Grey', 'layer', '#6B97AB'),
('Citadel', 'Warpstone Glow', 'layer', '#0F6F4E'),
('Citadel', 'Moot Green', 'layer', '#00B15B'),
('Citadel', 'Warboss Green', 'layer', '#3D8245'),
('Citadel', 'Skarsnik Green', 'layer', '#5A8144'),
('Citadel', 'Loren Forest', 'layer', '#50702F'),
('Citadel', 'Straken Green', 'layer', '#688E3B'),
('Citadel', 'Nurgling Green', 'layer', '#A0CC5A'),
('Citadel', 'Elysian Green', 'layer', '#6A9428'),
('Citadel', 'Ogryn Camo', 'layer', '#9BA77B'),
('Citadel', 'Ushabti Bone', 'layer', '#BBAF5F'),
('Citadel', 'Screaming Skull', 'layer', '#D5CA94'),
('Citadel', 'Tallarn Sand', 'layer', '#A58652'),
('Citadel', 'Kislev Flesh', 'layer', '#D19F64'),
('Citadel', 'Flayed One Flesh', 'layer', '#E5C297'),
('Citadel', 'Cadian Fleshtone', 'layer', '#C66F4D'),
('Citadel', 'Bestigor Flesh', 'layer', '#D39666'),
('Citadel', 'Ungor Flesh', 'layer', '#D6A568'),
('Citadel', 'Skrag Brown', 'layer', '#873E24'),
('Citadel', 'Deathclaw Brown', 'layer', '#B66D4D'),
('Citadel', 'Tau Light Ochre', 'layer', '#BC6B0C'),
('Citadel', 'Balor Brown', 'layer', '#876033'),
('Citadel', 'Zamesi Desert', 'layer', '#DAA26A'),
('Citadel', 'XV-88', 'layer', '#6C4811'),
('Citadel', 'Administratum Grey', 'layer', '#949B97'),
('Citadel', 'Eshin Grey', 'layer', '#494C50'),
('Citadel', 'Dawnstone', 'layer', '#6D7579'),
('Citadel', 'Stormvermin Fur', 'layer', '#827A66'),
('Citadel', 'Ulthuan Grey', 'layer', '#C3D0D1'),
('Citadel', 'White Scar', 'layer', '#FFFFFF'),
('Citadel', 'Pink Horror', 'layer', '#8F2C6B'),
('Citadel', 'Emperor''s Children', 'layer', '#B64E78'),
('Citadel', 'Fulgrim Pink', 'layer', '#EDA7C8'),
('Citadel', 'Xereus Purple', 'layer', '#48186A'),
('Citadel', 'Genestealer Purple', 'layer', '#7656A1'),
('Citadel', 'Warpfiend Grey', 'layer', '#716977'),

-- Citadel Shade Paints
('Citadel', 'Nuln Oil', 'shade', '#14100E'),
('Citadel', 'Agrax Earthshade', 'shade', '#523A26'),
('Citadel', 'Seraphim Sepia', 'shade', '#8E6840'),
('Citadel', 'Reikland Fleshshade', 'shade', '#975741'),
('Citadel', 'Carroburg Crimson', 'shade', '#AB003C'),
('Citadel', 'Druchii Violet', 'shade', '#3E205F'),
('Citadel', 'Drakenhof Nightshade', 'shade', '#194160'),
('Citadel', 'Coelia Greenshade', 'shade', '#006A6E'),
('Citadel', 'Biel-Tan Green', 'shade', '#00572C'),
('Citadel', 'Athonian Camoshade', 'shade', '#454A25'),
('Citadel', 'Casandora Yellow', 'shade', '#B77D00'),
('Citadel', 'Fuegan Orange', 'shade', '#D26D03'),

-- Citadel Dry Paints
('Citadel', 'Necron Compound', 'dry', '#878887'),
('Citadel', 'Longbeard Grey', 'dry', '#CCCAB4'),
('Citadel', 'Praxeti White', 'dry', '#FFFFFF'),
('Citadel', 'Terminatus Stone', 'dry', '#B5A993'),
('Citadel', 'Tyrant Skull', 'dry', '#CDC486'),
('Citadel', 'Eldar Flesh', 'dry', '#EEDFC0'),
('Citadel', 'Niblet Green', 'dry', '#8DB348'),
('Citadel', 'Underhive Ash', 'dry', '#C0B98A'),
('Citadel', 'Golgfag Brown', 'dry', '#A1663C'),
('Citadel', 'Verminlord Hide', 'dry', '#7A3A36'),
('Citadel', 'Changeling Pink', 'dry', '#F28EA8'),
('Citadel', 'Hexos Palesun', 'dry', '#FFEE92'),
('Citadel', 'Hellion Green', 'dry', '#82C543'),
('Citadel', 'Chronus Blue', 'dry', '#4FAACC'),
('Citadel', 'Etherium Blue', 'dry', '#A5D5E9'),
('Citadel', 'Skink Blue', 'dry', '#6FC6DC'),
('Citadel', 'Golden Griffon', 'dry', '#A6896F'),
('Citadel', 'Sigmarite', 'dry', '#DEB479'),

-- Citadel Technical Paints
('Citadel', 'Stirland Mud', 'technical', '#4F3A26'),
('Citadel', 'Astrogranite', 'technical', '#757679'),
('Citadel', 'Armageddon Dust', 'technical', '#957F4C'),
('Citadel', 'Mordant Earth', 'technical', '#403B30'),
('Citadel', 'Martian Ironearth', 'technical', '#8E442F'),
('Citadel', 'Agrellan Earth', 'technical', '#837760'),
('Citadel', '''Ardcoat', 'technical', NULL),
('Citadel', 'Lahmian Medium', 'technical', NULL),
('Citadel', 'Stormshield', 'technical', NULL),
('Citadel', 'Nihilakh Oxide', 'technical', '#68BCB4'),
('Citadel', 'Typhus Corrosion', 'technical', '#463D2F'),
('Citadel', 'Blood for the Blood God', 'technical', '#850F07'),
('Citadel', 'Waystone Green', 'technical', '#00C57C'),

-- Citadel Contrast Paints
('Citadel', 'Guilliman Flesh', 'contrast', '#F8B695'),
('Citadel', 'Darkoath Flesh', 'contrast', '#C67666'),
('Citadel', 'Apothecary White', 'contrast', '#FFFFFF'),
('Citadel', 'Skeleton Horde', 'contrast', '#D5C89A'),
('Citadel', 'Snakebite Leather', 'contrast', '#8A5B28'),
('Citadel', 'Gore-grunta Fur', 'contrast', '#6C3729'),
('Citadel', 'Cygor Brown', 'contrast', '#6B4720'),
('Citadel', 'Aggaros Dunes', 'contrast', '#CCA153'),
('Citadel', 'Iyanden Yellow', 'contrast', '#FBCE0C'),
('Citadel', 'Nazdreg Yellow', 'contrast', '#F9D100'),
('Citadel', 'Gryph-hound Orange', 'contrast', '#EC6909'),
('Citadel', 'Blood Angels Red', 'contrast', '#971319'),
('Citadel', 'Flesh Tearers Red', 'contrast', '#A7191E'),
('Citadel', 'Volupus Pink', 'contrast', '#BF3177'),
('Citadel', 'Shyish Purple', 'contrast', '#633C74'),
('Citadel', 'Magos Purple', 'contrast', '#823A84'),
('Citadel', 'Leviadon Blue', 'contrast', '#083953'),
('Citadel', 'Akhelian Green', 'contrast', '#0A5753'),
('Citadel', 'Dark Angels Green', 'contrast', '#004338'),
('Citadel', 'Militarum Green', 'contrast', '#596642'),
('Citadel', 'Creed Camo', 'contrast', '#A4906A'),
('Citadel', 'Ork Flesh', 'contrast', '#287A43'),
('Citadel', 'Warp Lightning', 'contrast', '#039D6A'),
('Citadel', 'Plaguebearer Flesh', 'contrast', '#92B475'),
('Citadel', 'Terradon Turquoise', 'contrast', '#008D86'),
('Citadel', 'Aethermatic Blue', 'contrast', '#4491CA'),
('Citadel', 'Talassar Blue', 'contrast', '#125D99'),
('Citadel', 'Space Wolves Grey', 'contrast', '#6F808C'),
('Citadel', 'Basilicanum Grey', 'contrast', '#7C869C'),
('Citadel', 'Garaghak''s Sewer', 'contrast', '#735D4C'),
('Citadel', 'Black Templar', 'contrast', '#11171C'),

-- Citadel Metallic Paints
('Citadel', 'Leadbelcher', 'base', '#888D8F'),
('Citadel', 'Iron Warriors', 'base', '#464854'),
('Citadel', 'Runelord Brass', 'layer', '#B77E45'),
('Citadel', 'Brass Scorpion', 'layer', '#A47552'),
('Citadel', 'Gehenna''s Gold', 'layer', '#BA7824'),
('Citadel', 'Auric Armour Gold', 'layer', '#E2AC5C'),
('Citadel', 'Retributor Armour', 'base', '#C39E56'),
('Citadel', 'Liberator Gold', 'layer', '#D1A95C'),
('Citadel', 'Stormhost Silver', 'layer', '#BBBFC0'),
('Citadel', 'Ironbreaker', 'layer', '#A1A8A6'),
('Citadel', 'Canoptek Alloy', 'layer', '#B6B9B5'),
('Citadel', 'Sycorax Bronze', 'layer', '#C1AF69')

ON CONFLICT (brand, name) DO NOTHING;
