-- Remove 9 paints not in the canonical 287-paint hobby-db catalog
-- These came from migration 000018 with different spellings/types than the CSV
-- WARNING: This will CASCADE delete any user_paints/recipe_steps referencing these paints

DELETE FROM public.paints
WHERE (brand, name, type) NOT IN (
  SELECT * FROM (VALUES
    ('Citadel', 'Abaddon Black', 'base'),
    ('Citadel', 'Administratum Grey', 'layer'),
    ('Citadel', 'Aeldari Emerald', 'contrast'),
    ('Citadel', 'Aethermatic Blue', 'contrast'),
    ('Citadel', 'Aggaros Dunes', 'contrast'),
    ('Citadel', 'Agrax Earthshade', 'shade'),
    ('Citadel', 'Agrellan Badland', 'technical'),
    ('Citadel', 'Agrellan Earth', 'technical'),
    ('Citadel', 'Ahriman Blue', 'layer'),
    ('Citadel', 'Akhelian Green', 'contrast'),
    ('Citadel', 'Alaitoc Blue', 'layer'),
    ('Citadel', 'Altdorf Guard Blue', 'layer'),
    ('Citadel', 'Apothecary White', 'contrast'),
    ('Citadel', 'Ardcoat', 'technical'),
    ('Citadel', 'Armageddon Dust', 'technical'),
    ('Citadel', 'Astorath Red', 'dry'),
    ('Citadel', 'Astrogranite', 'technical'),
    ('Citadel', 'Asurmen Blue', 'contrast'),
    ('Citadel', 'Athonian Camoshade', 'shade'),
    ('Citadel', 'Auric Armour Gold', 'layer'),
    ('Citadel', 'Averland Sunset', 'base'),
    ('Citadel', 'Baal Red', 'contrast'),
    ('Citadel', 'Bad Moon Yellow', 'contrast'),
    ('Citadel', 'Baharroth Blue', 'layer'),
    ('Citadel', 'Balor Brown', 'layer'),
    ('Citadel', 'Balthasar Gold', 'base'),
    ('Citadel', 'Baneblade Brown', 'layer'),
    ('Citadel', 'Barak-Nar Burgundy', 'base'),
    ('Citadel', 'Basilicanum Grey', 'contrast'),
    ('Citadel', 'Berserker Bloodshade', 'shade'),
    ('Citadel', 'Bestigor Flesh', 'layer'),
    ('Citadel', 'Biel-Tan Green', 'shade'),
    ('Citadel', 'Black Legion', 'contrast'),
    ('Citadel', 'Black Templar', 'contrast'),
    ('Citadel', 'Blood Angels Red', 'contrast'),
    ('Citadel', 'Blood For The Blood God', 'technical'),
    ('Citadel', 'Bloodreaver Flesh', 'layer'),
    ('Citadel', 'Blue Horror', 'layer'),
    ('Citadel', 'Brass Scorpion', 'layer'),
    ('Citadel', 'Briar Queen Chill', 'contrast'),
    ('Citadel', 'Bugman''s Glow', 'base'),
    ('Citadel', 'Cadian Fleshtone', 'layer'),
    ('Citadel', 'Caledor Sky', 'base'),
    ('Citadel', 'Calgar Blue', 'layer'),
    ('Citadel', 'Caliban Green', 'base'),
    ('Citadel', 'Canoptek Alloy', 'layer'),
    ('Citadel', 'Carroburg Crimson', 'shade'),
    ('Citadel', 'Casandora Yellow', 'shade'),
    ('Citadel', 'Castellan Green', 'base'),
    ('Citadel', 'Castellax Bronze', 'layer'),
    ('Citadel', 'Catachan Flesh', 'base'),
    ('Citadel', 'Celestium Blue', 'contrast'),
    ('Citadel', 'Celestra Grey', 'base'),
    ('Citadel', 'Chaos Black', 'spray'),
    ('Citadel', 'Coelia Greenshade', 'shade'),
    ('Citadel', 'Contrast Medium', 'technical'),
    ('Citadel', 'Corax White', 'base'),
    ('Citadel', 'Corvus Black', 'base'),
    ('Citadel', 'Creed Camo', 'contrast'),
    ('Citadel', 'Cygor Brown', 'contrast'),
    ('Citadel', 'Daemonette Hide', 'base'),
    ('Citadel', 'Dark Angels Green', 'contrast'),
    ('Citadel', 'Dark Reaper', 'layer'),
    ('Citadel', 'Darkoath Flesh', 'contrast'),
    ('Citadel', 'Dawnstone', 'dry'),
    ('Citadel', 'Dawnstone', 'layer'),
    ('Citadel', 'Death Guard Green', 'base'),
    ('Citadel', 'Death Guard Green', 'spray'),
    ('Citadel', 'Death Korps Drab', 'base'),
    ('Citadel', 'Deathclaw Brown', 'layer'),
    ('Citadel', 'Deathworld Forest', 'base'),
    ('Citadel', 'Dechala Lilac', 'layer'),
    ('Citadel', 'Deepkin Flesh', 'layer'),
    ('Citadel', 'Doombull Brown', 'layer'),
    ('Citadel', 'Doomfire Magenta', 'contrast'),
    ('Citadel', 'Dorn Yellow', 'layer'),
    ('Citadel', 'Drakenhof Nightshade', 'shade'),
    ('Citadel', 'Dreadful Visage', 'contrast'),
    ('Citadel', 'Druchii Violet', 'shade'),
    ('Citadel', 'Dryad Bark', 'base'),
    ('Citadel', 'Eldar Flesh', 'dry'),
    ('Citadel', 'Elysian Green', 'layer'),
    ('Citadel', 'Emperor''s Children', 'layer'),
    ('Citadel', 'Eshin Grey', 'layer'),
    ('Citadel', 'Etherium Blue', 'dry'),
    ('Citadel', 'Evil Sunz Scarlet', 'layer'),
    ('Citadel', 'Fenrisian Grey', 'layer'),
    ('Citadel', 'Fire Dragon Bright', 'layer'),
    ('Citadel', 'Flash Gitz Yellow', 'layer'),
    ('Citadel', 'Flayed One Flesh', 'layer'),
    ('Citadel', 'Flesh Tearers Red', 'contrast'),
    ('Citadel', 'Frostheart', 'contrast'),
    ('Citadel', 'Fuegan Orange', 'shade'),
    ('Citadel', 'Fulgrim Pink', 'layer'),
    ('Citadel', 'Fulgurite Copper', 'layer'),
    ('Citadel', 'Fyreslayer Flesh', 'contrast'),
    ('Citadel', 'Gal Vorbak Red', 'base'),
    ('Citadel', 'Garaghak''s Sewer', 'contrast'),
    ('Citadel', 'Gauss Blaster Green', 'layer'),
    ('Citadel', 'Gehenna''s Gold', 'layer'),
    ('Citadel', 'Genestealer Purple', 'layer'),
    ('Citadel', 'Golden Griffon', 'dry'),
    ('Citadel', 'Golgfag Brown', 'dry'),
    ('Citadel', 'Gore-Grunta Fur', 'contrast'),
    ('Citadel', 'Gorthor Brown', 'layer'),
    ('Citadel', 'Grey Knights Steel', 'base'),
    ('Citadel', 'Grey Seer', 'base'),
    ('Citadel', 'Grey Seer', 'spray'),
    ('Citadel', 'Gryph-Charger Grey', 'contrast'),
    ('Citadel', 'Gryph-Hound Orange', 'contrast'),
    ('Citadel', 'Guilliman Flesh', 'contrast'),
    ('Citadel', 'Gutrippa Flesh', 'contrast'),
    ('Citadel', 'Hashut Copper', 'layer'),
    ('Citadel', 'Hexos Palesun', 'dry'),
    ('Citadel', 'Hexwraith Flame', 'contrast'),
    ('Citadel', 'Hobgrot Hide', 'base'),
    ('Citadel', 'Hoeth Blue', 'dry'),
    ('Citadel', 'Hoeth Blue', 'layer'),
    ('Citadel', 'Imperial Fist', 'contrast'),
    ('Citadel', 'Imrik Blue', 'dry'),
    ('Citadel', 'Incubi Darkness', 'base'),
    ('Citadel', 'Ionrach Skin', 'base'),
    ('Citadel', 'Iron Hands Steel', 'base'),
    ('Citadel', 'Iron Warriors', 'base'),
    ('Citadel', 'Ironbreaker', 'layer'),
    ('Citadel', 'Ironjawz Yellow', 'contrast'),
    ('Citadel', 'Iyanden Yellow', 'contrast'),
    ('Citadel', 'Jokaero Orange', 'base'),
    ('Citadel', 'Kabalite Green', 'layer'),
    ('Citadel', 'Kakophoni Purple', 'layer'),
    ('Citadel', 'Kantor Blue', 'base'),
    ('Citadel', 'Karak Stone', 'layer'),
    ('Citadel', 'Karandras Green', 'contrast'),
    ('Citadel', 'Khorne Red', 'base'),
    ('Citadel', 'Kislev Flesh', 'layer'),
    ('Citadel', 'Knight-Questor Flesh', 'layer'),
    ('Citadel', 'Krieg Khaki', 'layer'),
    ('Citadel', 'Kroak Green', 'shade'),
    ('Citadel', 'Kroxigor Scales', 'contrast'),
    ('Citadel', 'Lahmian Medium', 'technical'),
    ('Citadel', 'Leadbelcher', 'base'),
    ('Citadel', 'Leadbelcher', 'spray'),
    ('Citadel', 'Leviadon Blue', 'contrast'),
    ('Citadel', 'Leviathan Purple', 'contrast'),
    ('Citadel', 'Liberator Gold', 'layer'),
    ('Citadel', 'Longbeard Grey', 'dry'),
    ('Citadel', 'Loren Forest', 'layer'),
    ('Citadel', 'Lothern Blue', 'layer'),
    ('Citadel', 'Lucius Lilac', 'dry'),
    ('Citadel', 'Lugganath Orange', 'layer'),
    ('Citadel', 'Lupercal Green', 'base'),
    ('Citadel', 'Luxion Purple', 'contrast'),
    ('Citadel', 'Macragge Blue', 'base'),
    ('Citadel', 'Macragge Blue', 'spray'),
    ('Citadel', 'Magmadroth Flame', 'contrast'),
    ('Citadel', 'Magos Purple', 'contrast'),
    ('Citadel', 'Mantis Warriors Green', 'contrast'),
    ('Citadel', 'Martian Ironcrust', 'technical'),
    ('Citadel', 'Martian Ironearth', 'technical'),
    ('Citadel', 'Mechanicus Standard Grey', 'base'),
    ('Citadel', 'Mechanicus Standard Grey', 'spray'),
    ('Citadel', 'Mephiston Red', 'base'),
    ('Citadel', 'Mephiston Red', 'spray'),
    ('Citadel', 'Militarum Green', 'contrast'),
    ('Citadel', 'Moot Green', 'layer'),
    ('Citadel', 'Mordant Earth', 'technical'),
    ('Citadel', 'Morghast Bone', 'base'),
    ('Citadel', 'Mortarion Grime', 'shade'),
    ('Citadel', 'Mournfang Brown', 'base'),
    ('Citadel', 'Munitorum Varnish', 'spray'),
    ('Citadel', 'Naggaroth Night', 'base'),
    ('Citadel', 'Nazdreg Yellow', 'contrast'),
    ('Citadel', 'Necron Compound', 'dry'),
    ('Citadel', 'Niblet Green', 'dry'),
    ('Citadel', 'Night Lords Blue', 'base'),
    ('Citadel', 'Nighthaunt Gloom', 'contrast'),
    ('Citadel', 'Nihilakh Oxide', 'technical'),
    ('Citadel', 'Nocturne Green', 'base'),
    ('Citadel', 'Nuln Oil', 'shade'),
    ('Citadel', 'Nurgles Rot', 'technical'),
    ('Citadel', 'Nurgling Green', 'dry'),
    ('Citadel', 'Nurgling Green', 'layer'),
    ('Citadel', 'Ogryn Camo', 'layer'),
    ('Citadel', 'Ork Flesh', 'contrast'),
    ('Citadel', 'Orruk Flesh', 'base'),
    ('Citadel', 'Pallid Wych Flesh', 'layer'),
    ('Citadel', 'Phalanx Yellow', 'layer'),
    ('Citadel', 'Phoenician Purple', 'base'),
    ('Citadel', 'Pink Horror', 'layer'),
    ('Citadel', 'Plaguebearer Flesh', 'contrast'),
    ('Citadel', 'Poxwalker', 'shade'),
    ('Citadel', 'Praxeti White', 'dry'),
    ('Citadel', 'Pylar Glacier', 'contrast'),
    ('Citadel', 'Rakarth Flesh', 'base'),
    ('Citadel', 'Ratling Grime', 'contrast'),
    ('Citadel', 'Ratskin Flesh', 'base'),
    ('Citadel', 'Reikland Fleshshade', 'shade'),
    ('Citadel', 'Retributor Armour', 'base'),
    ('Citadel', 'Retributor Armour', 'spray'),
    ('Citadel', 'Rhinox Hide', 'base'),
    ('Citadel', 'Runefang Steel', 'layer'),
    ('Citadel', 'Runelord Brass', 'base'),
    ('Citadel', 'Russ Grey', 'layer'),
    ('Citadel', 'Ryza Rust', 'dry'),
    ('Citadel', 'Screamer Pink', 'base'),
    ('Citadel', 'Screaming Bell', 'base'),
    ('Citadel', 'Screaming Skull', 'layer'),
    ('Citadel', 'Seraphim Sepia', 'shade'),
    ('Citadel', 'Shyish Purple', 'contrast'),
    ('Citadel', 'Sigmarite', 'dry'),
    ('Citadel', 'Sigvald Burgundy', 'contrast'),
    ('Citadel', 'Skarsnik Green', 'layer'),
    ('Citadel', 'Skavenblight Dinge', 'layer'),
    ('Citadel', 'Skeleton Horde', 'contrast'),
    ('Citadel', 'Skink Blue', 'dry'),
    ('Citadel', 'Skrag Brown', 'layer'),
    ('Citadel', 'Skullcrusher Brass', 'layer'),
    ('Citadel', 'Slaanesh Grey', 'layer'),
    ('Citadel', 'Snakebite Leather', 'contrast'),
    ('Citadel', 'Sons of Horus Green', 'layer'),
    ('Citadel', 'Sotek Green', 'layer'),
    ('Citadel', 'Soulblight Grey', 'shade'),
    ('Citadel', 'Soulstone Blue', 'technical'),
    ('Citadel', 'Space Wolves Grey', 'contrast'),
    ('Citadel', 'Spiritstone Red', 'technical'),
    ('Citadel', 'Squig Orange', 'layer'),
    ('Citadel', 'Steel Legion Drab', 'base'),
    ('Citadel', 'Stegadon Scale Green', 'base'),
    ('Citadel', 'Stirland Mud', 'technical'),
    ('Citadel', 'Stormfang', 'dry'),
    ('Citadel', 'Stormfiend', 'contrast'),
    ('Citadel', 'Stormhost Silver', 'layer'),
    ('Citadel', 'Stormshield', 'technical'),
    ('Citadel', 'Stormvermin Fur', 'layer'),
    ('Citadel', 'Straken Green', 'layer'),
    ('Citadel', 'Striking Scorpion Green', 'contrast'),
    ('Citadel', 'Sybarite Green', 'layer'),
    ('Citadel', 'Sycorax Bronze', 'layer'),
    ('Citadel', 'Sylvaneth Bark', 'dry'),
    ('Citadel', 'Talassar Blue', 'contrast'),
    ('Citadel', 'Tallarn Sand', 'layer'),
    ('Citadel', 'Targor Rageshade', 'shade'),
    ('Citadel', 'Tau Light Ochre', 'layer'),
    ('Citadel', 'Teclis Blue', 'layer'),
    ('Citadel', 'Temple Guard Blue', 'layer'),
    ('Citadel', 'Terminatus Stone', 'dry'),
    ('Citadel', 'Terradon Turquoise', 'contrast'),
    ('Citadel', 'Tesseract Glow', 'technical'),
    ('Citadel', 'The Fang', 'base'),
    ('Citadel', 'Thondia Brown', 'base'),
    ('Citadel', 'Thousand Sons Blue', 'base'),
    ('Citadel', 'Thunderhawk Blue', 'layer'),
    ('Citadel', 'Troll Slayer Orange', 'layer'),
    ('Citadel', 'Tuskgor Fur', 'layer'),
    ('Citadel', 'Typhus Corrosion', 'technical'),
    ('Citadel', 'Tyran Blue', 'shade'),
    ('Citadel', 'Tyrant Skull', 'dry'),
    ('Citadel', 'Ulthuan Grey', 'layer'),
    ('Citadel', 'Ultramarines Blue', 'contrast'),
    ('Citadel', 'Underhive Ash', 'dry'),
    ('Citadel', 'Ungor Flesh', 'layer'),
    ('Citadel', 'Ushabti Bone', 'layer'),
    ('Citadel', 'Valhallan Blizzard', 'technical'),
    ('Citadel', 'Volupus Pink', 'contrast'),
    ('Citadel', 'Vulkan Green', 'layer'),
    ('Citadel', 'Waaagh! Flesh', 'base'),
    ('Citadel', 'Warboss Green', 'layer'),
    ('Citadel', 'Warp Lightning', 'contrast'),
    ('Citadel', 'Warpfiend Grey', 'layer'),
    ('Citadel', 'Warplock Bronze', 'base'),
    ('Citadel', 'Warpstone Glow', 'layer'),
    ('Citadel', 'Waystone Green', 'technical'),
    ('Citadel', 'Wazdakka Red', 'layer'),
    ('Citadel', 'White Scar', 'layer'),
    ('Citadel', 'White Scar', 'spray'),
    ('Citadel', 'Wild Rider Red', 'layer'),
    ('Citadel', 'Word Bearers Red', 'layer'),
    ('Citadel', 'Wrack White', 'dry'),
    ('Citadel', 'Wraithbone', 'base'),
    ('Citadel', 'Wraithbone', 'spray'),
    ('Citadel', 'Wyldwood', 'contrast'),
    ('Citadel', 'Xereus Purple', 'layer'),
    ('Citadel', 'XV-88', 'base'),
    ('Citadel', 'Yriel Yellow', 'layer'),
    ('Citadel', 'Zamesi Desert', 'layer'),
    ('Citadel', 'Zandri Dust', 'base'),
    ('Citadel', 'Zandri Dust', 'spray')
  ) AS t(brand, name, type)
);
